# Generated by Django 3.1.2 on 2020-10-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='content2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
